### ISSUE TITLE
Throwing error while trying to use angular-redux

### ISSUE THREAD

**Issue by RAJKUMAR996** [angular-redux/platform#92]
### This is a...
- [x] bug report

### Environment

NodeJS Version: v8.12.0
Typescript Version:3.2.2
Angular Version:7.2.0
@angular-redux/store version:10.0.0
redux Version:4.0.2

### Stack Trace/Error Message:

ERROR in node_modules/@angular-redux/store/components/ng-redux.d.ts(10,31): error TS2420: Class 'NgRedux<RootState>' incorrectly implements interface 'ObservableStore<RootState>'.
  Property '[Symbol.observable]' is missing in type 'NgRedux<RootState>' but required in type 'ObservableStore<RootState>'.

### Additional Notes:
seems like store interface got updated in latest release of Redux (4.0.2)

**Comment by ilkkaparssinen** [comment]
Got same error with @angular-redux/store 9.0.0 and redux 4.0.3. Downgrading to redux 4.0.1 solved the situation for me.

**Comment by doanthai** [comment]
Same issue: https://github.com/angular-redux/platform/issues/93

**Comment by caipirginka** [comment]
Yes, I can confirm that redux@4.0.1 works with latest @angular-redux.
There seems to be a specular issue on redux side: [https://github.com/reduxjs/redux/issues/3466](https://github.com/reduxjs/redux/issues/3466)
But I didn't understand if this is indeed a bug inside redux and it will get corrected in a future version, or if it is a bug inside angular-redux that needs to be modified to keep it working with redux >= 4.0.2

**Comment by nivrith** [comment]
Yes, same after downgrading to redux@4.0.1 it works with latest @angular-redux for me

**Comment by SteppeEagle** [comment]
the same for me. I spent a lot of time for fixing it.
