### ISSUE TITLE
angular-redux/store error with won't compile with rxjs 6.4.0

### ISSUE THREAD

**Issue by rmorrise** [angular-redux/platform#101]
### This is a...

- [x] bug report

### What toolchain are you using for transpilation/bundling?

- [x] @angular/cli

### Environment

NodeJS Version: 12.10.0
Typescript Version: 3.5.3
Angular Version: 8.2.7
@angular-redux/store version: 10.0.0
@angular/cli version: (if applicable) 8.3.5
OS: Win10 Enterprise x64

### Expected Behaviour:

Should compile normally.

### Actual Behaviour:

Error running ```ng test --source-map false```

### Stack Trace/Error Message:

```
ERROR in node_modules/@angular-redux/store/components/ng-redux.d.ts:10:31 - error TS2420: Class 'NgRedux<RootState>' incorrectly implements interface 'ObservableStore<RootSta
te>'.
  Property '[Symbol.observable]' is missing in type 'NgRedux<RootState>' but required in type 'ObservableStore<RootState>'.

10 export declare abstract class NgRedux<RootState> implements ObservableStore<RootState> {
                                 ~~~~~~~

  node_modules/redux/index.d.ts:247:3
    247   [Symbol.observable](): Observable<S>
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    '[Symbol.observable]' is declared here.
```

### Additional Notes:

    "rxjs": "~6.4.0"

**Comment by LukasKlement** [comment]
You need to downgrade to redux 4.0.1 to compile your project, see this comment [here](https://github.com/angular-redux/platform/issues/90#issuecomment-509835001) or [here](https://github.com/angular-redux/platform/issues/92#issuecomment-513060672).
